exports.dummyData = [
  {
    inputIndex: 0,
    candidateIndex: 0,
    deliveryLine1: '234 Kalamazoooo',
    lastLine: 'Orlando FL 32817-4801',
    deliveryPointBarcode: '328174801088',
    components: {
      primaryNumber: '234',
      streetName: 'Kalamazoooo',
      streetSuffix: '',
      cityName: 'Orlando',
      defaultCityName: 'Orlando',
      state: 'FL',
      zipCode: '32817',
      plus4Code: '4801',
      deliveryPoint: '08',
      deliveryPointCheckDigit: '8',
    },
    metadata: {
      recordType: 'S',
      zipType: 'Standard',
      countyFips: '12095',
      countyName: 'Orange',
      carrierRoute: 'C020',
      congressionalDistrict: '07',
      rdi: 'Residential',
      elotSequence: '0147',
      elotSort: 'A',
      latitude: 28.57544,
      longitude: -81.23714,
      precision: 'Zip9',
      timeZone: 'Eastern',
      utcOffset: -5,
      obeysDst: true,
    },
    analysis: {
      dpvMatchCode: 'Y',
      dpvFootnotes: 'AABB',
      cmra: 'N',
      vacant: 'N',
      active: 'Y',
    },
  },
  {
    inputIndex: 0,
    candidateIndex: 0,
    deliveryLine1: '10308 Kennebec Ct',
    lastLine: 'Orlando FL 32817-4801',
    deliveryPointBarcode: '328174801088',
    components: {
      primaryNumber: '10308',
      streetName: 'Kennebec',
      streetSuffix: 'Ct',
      cityName: 'Orlando',
      defaultCityName: 'Orlando',
      state: 'FL',
      zipCode: '32817',
      plus4Code: '4801',
      deliveryPoint: '08',
      deliveryPointCheckDigit: '8',
    },
    metadata: {
      recordType: 'S',
      zipType: 'Standard',
      countyFips: '12095',
      countyName: 'Orange',
      carrierRoute: 'C020',
      congressionalDistrict: '07',
      rdi: 'Residential',
      elotSequence: '0147',
      elotSort: 'A',
      latitude: 28.57544,
      longitude: -81.23714,
      precision: 'Zip9',
      timeZone: 'Eastern',
      utcOffset: -5,
      obeysDst: true,
    },
    analysis: {
      dpvMatchCode: 'Y',
      dpvFootnotes: 'AABB',
      cmra: 'N',
      vacant: 'N',
      active: 'Y',
    },
  },
  {
    inputIndex: 0,
    candidateIndex: 0,
    deliveryLine1: '10308 Kennebec Ct',
    lastLine: 'Orlando FL 32817-4801',
    deliveryPointBarcode: '328174801088',
    components: {
      primaryNumber: '10308',
      streetName: 'Kennebec',
      streetSuffix: 'Ct',
      cityName: 'Orlando',
      defaultCityName: 'Orlando',
      state: 'FL',
      zipCode: '32817',
      plus4Code: '4801',
      deliveryPoint: '08',
      deliveryPointCheckDigit: '8',
    },
    metadata: {
      recordType: 'S',
      zipType: 'Standard',
      countyFips: '12095',
      countyName: 'Orange',
      carrierRoute: 'C020',
      congressionalDistrict: '07',
      rdi: 'Residential',
      elotSequence: '0147',
      elotSort: 'A',
      latitude: 28.57544,
      longitude: -81.23714,
      precision: 'Zip9',
      timeZone: 'Eastern',
      utcOffset: -5,
      obeysDst: true,
    },
    analysis: {
      dpvMatchCode: 'Y',
      dpvFootnotes: 'AABB',
      cmra: 'N',
      vacant: 'N',
      active: 'Y',
    },
  },
  {
    inputIndex: 0,
    candidateIndex: 0,
    deliveryLine1: '10308 Kennebec Ct',
    lastLine: 'Orlando FL 32817-4801',
    deliveryPointBarcode: '328174801088',
    components: {
      primaryNumber: '10308',
      streetName: 'Kennebec',
      streetSuffix: 'Ct',
      cityName: 'Orlando',
      defaultCityName: 'Orlando',
      state: 'FL',
      zipCode: '32817',
      plus4Code: '4801',
      deliveryPoint: '08',
      deliveryPointCheckDigit: '8',
    },
    metadata: {
      recordType: 'S',
      zipType: 'Standard',
      countyFips: '12095',
      countyName: 'Orange',
      carrierRoute: 'C020',
      congressionalDistrict: '07',
      rdi: 'Residential',
      elotSequence: '0147',
      elotSort: 'A',
      latitude: 28.57544,
      longitude: -81.23714,
      precision: 'Zip9',
      timeZone: 'Eastern',
      utcOffset: -5,
      obeysDst: true,
    },
    analysis: {
      dpvMatchCode: 'Y',
      dpvFootnotes: 'AABB',
      cmra: 'N',
      vacant: 'N',
      active: 'Y',
    },
  },
  {
    inputIndex: 0,
    candidateIndex: 0,
    deliveryLine1: '10308 Kennebec Ct',
    lastLine: 'Orlando FL 32817-4801',
    deliveryPointBarcode: '328174801088',
    components: {
      primaryNumber: '10308',
      streetName: 'Kennebec',
      streetSuffix: 'Ct',
      cityName: 'Orlando',
      defaultCityName: 'Orlando',
      state: 'FL',
      zipCode: '32817',
      plus4Code: '4801',
      deliveryPoint: '08',
      deliveryPointCheckDigit: '8',
    },
    metadata: {
      recordType: 'S',
      zipType: 'Standard',
      countyFips: '12095',
      countyName: 'Orange',
      carrierRoute: 'C020',
      congressionalDistrict: '07',
      rdi: 'Residential',
      elotSequence: '0147',
      elotSort: 'A',
      latitude: 28.57544,
      longitude: -81.23714,
      precision: 'Zip9',
      timeZone: 'Eastern',
      utcOffset: -5,
      obeysDst: true,
    },
    analysis: {
      dpvMatchCode: 'Y',
      dpvFootnotes: 'AABB',
      cmra: 'N',
      vacant: 'N',
      active: 'Y',
    },
  },
  {
    inputIndex: 0,
    candidateIndex: 0,
    deliveryLine1: '10308 Kennebec Ct',
    lastLine: 'Orlando FL 32817-4801',
    deliveryPointBarcode: '328174801088',
    components: {
      primaryNumber: '10308',
      streetName: 'Kennebec',
      streetSuffix: 'Ct',
      cityName: 'Orlando',
      defaultCityName: 'Orlando',
      state: 'FL',
      zipCode: '32817',
      plus4Code: '4801',
      deliveryPoint: '08',
      deliveryPointCheckDigit: '8',
    },
    metadata: {
      recordType: 'S',
      zipType: 'Standard',
      countyFips: '12095',
      countyName: 'Orange',
      carrierRoute: 'C020',
      congressionalDistrict: '07',
      rdi: 'Residential',
      elotSequence: '0147',
      elotSort: 'A',
      latitude: 28.57544,
      longitude: -81.23714,
      precision: 'Zip9',
      timeZone: 'Eastern',
      utcOffset: -5,
      obeysDst: true,
    },
    analysis: {
      dpvMatchCode: 'Y',
      dpvFootnotes: 'AABB',
      cmra: 'N',
      vacant: 'N',
      active: 'Y',
    },
  },
];
